<?php

namespace App\Infrastructure\Nginx;

/**
 * Generates nginx configuration for streaming and admin.
 * Used for multi-node or LB deployments (ARCHITECTURE.md §4.6, §8).
 */
class NginxConfigGenerator
{
    public function __construct(
        private string $templatePath = ''
    ) {
        if ($this->templatePath === '') {
            $this->templatePath = base_path('infrastructure/nginx/templates');
        }
    }

    /**
     * Generate main nginx config snippet for streaming locations.
     */
    public function generate(array $servers = [], array $streams = []): string
    {
        $lines = [];
        $lines[] = '# Generated by NginxConfigGenerator';
        $lines[] = 'location ~ ^/(live|movie|series|timeshift|streaming)/ {';
        $lines[] = '    try_files $uri $uri/ /stream.php?$query_string;';
        $lines[] = '    fastcgi_split_path_info ^(.+\.php)(/.+)$;';
        $lines[] = '    fastcgi_pass unix:/run/php/php-fpm.sock;';
        $lines[] = '    include fastcgi_params;';
        $lines[] = '    fastcgi_param SCRIPT_FILENAME $document_root/stream.php;';
        $lines[] = '}';
        return implode("\n", $lines);
    }

    public function reload(): bool
    {
        $output = [];
        $code = 0;
        @exec('nginx -t 2>&1 && nginx -s reload 2>&1', $output, $code);
        return $code === 0;
    }
}
